#!/usr/bin/env bash
set -e
#

#A script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)
if [ "$current_profile" == "performance" ]
 then
     echo "<span font='FontAwesome' color='yellow'></span>"
 elif [ "$current_profile" == "balanced" ]
 then
     echo "<span font='FontAwesome' color='white'></span>"
 elif [ "$current_profile" == "power-saver" ]
 then
     echo "<span font='FontAwesome' color='green'></span>"
 else
     echo "<span font='FontAwesome' color='red'></span>"
fi

